name: reporter_api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  get_it: ^7.6.4
  freezed: ^2.4.5
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
